---
- name: Ensure services are disabled
  ansible.builtin.service:
    name: pve-ha-lrm
    state: "disable_services and 'stopped' or 'started'"
    enabled: not disable_services

- name: Ensure services are disabled
  ansible.builtin.service:
    name: pve-ha-crm
    state: "disable_services and 'stopped' or 'started'"
    enabled: not disable_services

- name: Ensure services are disabled
  ansible.builtin.service:
    name: corosync
    state: "disable_services and 'stopped' or 'started'"
    enabled: not disable_services
  failed_when: false
