---
- name: Ensure HA services are enabled or disabled based on configuration
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: "{{ 'started' if proxmox_enable_ha_services else 'stopped' }}"
    enabled: "{{ proxmox_enable_ha_services }}"
  loop:
    - pve-ha-lrm
    - pve-ha-crm
    - corosync
  failed_when: false
