---
# tasks file for ansible-proxmox
- name: Update cache if needed (Debian)
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Ensure packages are installed
  ansible.builtin.apt:
    name:
      - neofetch
      - htop
      - iotop
      - ifupdown2
    state: present

- name: Comment Cepth repository
  ansible.builtin.replace:
    path: /etc/apt/sources.list.d/ceph.list
    regexp: "^deb"
    replace: "#deb"

- name: Comment enterprise repository
  ansible.builtin.replace:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: "^deb"
    replace: "#deb"

- name: Create community repository
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/pve-community.list
    content: "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"

- name: Ensure enterprise repository is removed
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent

- name: Disable subscription nag script
  ansible.builtin.copy:
    src: no-nag-script
    dest: /etc/apt/apt.conf.d/no-nag-script
    owner: root
    group: root
    mode: "0755"
  notify: Reinstall proxmox-widget-toolkit

- name: Disable/enable services for HA (SSD lifetime)
  ansible.builtin.import_tasks: disable-services.yml

- name: Enable Proxmox Backup Client
  ansible.builtin.import_tasks: pbs-client.yml
  when: proxmox_enable_pbs_client

- name: Disable Proxmox Backup Client
  ansible.builtin.cron:
    name: "run file folder backup"
    state: absent
  when: not proxmox_enable_pbs_client

- name: Enable notfications
  ansible.builtin.import_tasks: notifications.yml
