---
# tasks file for ansible-proxmox
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Ensure packages are installed
  ansible.builtin.apt:
    name:
      - neofetch
      - htop
      - iotop
      - nethogs
      - ifupdown2
    state: present

- name: Disable Proxmox Enterprise repository
  ansible.builtin.replace:
    path: /etc/apt/sources.list.d/pve-enterprise.sources
    regexp: "^Enabled: true"
    replace: "Enabled: false"

- name: Add Proxmox Community repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/pve-no-subscription.sources
    owner: root
    group: root
    mode: "0644"
    content: |
      Types: deb
      URIs: http://download.proxmox.com/debian/pve/
      Suites: trixie
      Components: pve-no-subscription
      Signed-By: /usr/share/keyrings/proxmox-archive-keyring.gpg

- name: Disable subscription nag script
  ansible.builtin.copy:
    src: no-nag-script
    dest: /etc/apt/apt.conf.d/no-nag-script
    owner: root
    group: root
    mode: "0755"
  notify: Reinstall proxmox-widget-toolkit

- name: Import tasks to disable or enable services for HA (SSD lifetime)
  ansible.builtin.import_tasks: disable-services.yml

- name: Enable Proxmox Backup Client if specified
  ansible.builtin.import_tasks: pbs-client.yml
  when: proxmox_enable_pbs_client

- name: Disable Proxmox Backup Client cron job if not enabled
  ansible.builtin.cron:
    name: "run file folder backup"
    state: absent
  when: not proxmox_enable_pbs_client

- name: Enable notifications
  ansible.builtin.import_tasks: notifications.yml
