---
- name: Ensure necessary packages are installed
  ansible.builtin.apt:
    name:
      - libsasl2-modules
      - mailutils
    state: present

- name: Ensure password file is present
  ansible.builtin.copy:
    dest: /etc/postfix/sasl_passwd
    content: "{{ proxmox_smtp.host }} {{ proxmox_smtp.email }}:{{ proxmox_smtp.password }}"
    mode: "0600"
  notify: Restart postfix

- name: Ensure credentials database is present
  ansible.builtin.command: postmap hash:/etc/postfix/sasl_passwd
  changed_when: false

- name: Ensure relayhost is commented in main.cf
  ansible.builtin.lineinfile:
    path: /etc/postfix/main.cf
    regexp: "^relayhost ="
    line: "#relayhost ="
    state: present
  notify: Restart postfix

- name: Ensure SMTP configuration is in Postfix config
  ansible.builtin.blockinfile:
    path: /etc/postfix/main.cf
    block: |
      relayhost = {{ proxmox_smtp.host }}:{{ proxmox_smtp.port }}
      smtp_use_tls = yes
      smtp_sasl_auth_enable = yes
      smtp_sasl_security_options =
      smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
      smtp_tls_CAfile = /etc/ssl/certs/Entrust_Root_Certification_Authority.pem
      smtp_tls_session_cache_database = btree:/var/lib/postfix/smtp_tls_session_cache
      smtp_tls_session_cache_timeout = 3600s
  notify: Restart postfix
