---
- name: Add Proxmox Backup repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/pbs-client.sources
    owner: root
    group: root
    mode: "0644"
    content: |
      Types: deb
      URIs: http://download.proxmox.com/debian/pbs-client/
      Suites: trixie
      Components: main
      Signed-By: /usr/share/keyrings/proxmox-archive-keyring.gpg

- name: Install Proxmox Backup Client
  ansible.builtin.package:
    name:
      - proxmox-backup-client
    state: present

- name: Copy file backup script is on remote
  ansible.builtin.template:
    src: pbs-proxmox-backup.sh.j2
    dest: /root/pbs-proxmox-backup.sh
    mode: "0755"
    owner: root
    group: root

- name: Ensure file backup cron is present
  ansible.builtin.cron:
    name: "run file folder backup"
    minute: "0"
    hour: "{{ proxmox_backup_hours }}"
    job: "/root/pbs-proxmox-backup.sh"
