---
# handlers file for ansible-proxmox
- name: Restart postfix
  ansible.builtin.command: "postfix reload"
  changed_when: true

- name: Restart pveproxy
  ansible.builtin.systemd:
    name: pveproxy
    state: restarted
    daemon_reload: true

- name: Reinstall proxmox-widget-toolkit
  ansible.builtin.command: apt --reinstall install proxmox-widget-toolkit
  changed_when: true
