---
# handlers file for ansible-proxmox
- name: Restart postfix
  ansible.builtin.command: "postfix reload"
  changed_when: true

- name: Restart pveproxy
  ansible.builtin.service:
    name: pveproxy
    state: restarted
